// @ts-check
import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  // `icon-paths.ts` is generated by scripts/gen-icons-ts.mjs; linting generated
  // code only produces noise, and `dist/` is a build product.
  { ignores: ['dist/', 'node_modules/', 'src/ui/icon-paths.ts'] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['scripts/**', 'eslint.config.mjs'],
    languageOptions: { globals: globals.node },
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      // The services deliberately pre-initialise locals (`let tab = null`)
      // before a try block whose catch returns — the clearest spelling of
      // "this binding always holds a value past this point" — and the rule
      // reads that intent as a dead store.
      'no-useless-assignment': 'off',
    },
  },
);
