/**
 * Build pipeline.
 *
 * Bundles the three TypeScript entry points, then assembles `dist/` as a
 * loadable unpacked extension:
 *
 *   dist/manifest.json          version synced from package.json
 *   dist/background/index.js    service worker (ES module)
 *   dist/popup/…                popup document + bundle + styles
 *   dist/options/…              options document + bundle + styles
 *   dist/assets/icons/*.png     generated by generate-icons.mjs
 *   dist/ui/styles/*.css        shared design system, copied verbatim
 *
 * Run with `--watch` for incremental rebuilds.
 */

import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, extname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import * as esbuild from 'esbuild';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src');
const DIST = join(ROOT, 'dist');

const WATCH = process.argv.includes('--watch');

/** Every bundle the extension needs. */
const BUNDLES = [
  { entry: 'background/index.ts', out: 'background/index.js' },
  { entry: 'popup/main.ts', out: 'popup/main.js' },
  { entry: 'options/main.ts', out: 'options/main.js' },
];

/** Static assets copied as-is. Directories recurse; files are placed verbatim. */
const STATIC = [
  { from: 'manifest.json', to: 'manifest.json', transform: stampVersion },
  { from: 'popup/popup.html', to: 'popup/popup.html' },
  { from: 'options/options.html', to: 'options/options.html' },
  { from: 'assets/icons', to: 'assets/icons' },
];

/**
 * Shared design-system stylesheets, in cascade order. They are prepended to each
 * page's own CSS rather than linked separately.
 *
 * Why concatenate instead of four <link> tags: a page that renders with some of
 * its stylesheets missing is close to undebuggable — layout survives, so it looks
 * like a design bug rather than a failed request, and it survives a reload
 * because Chrome caches extension resources aggressively. One stylesheet per
 * page removes the entire failure mode and removes four round-trips besides.
 */
const SHARED_STYLES = [
  { file: 'tokens.css', title: 'Design tokens' },
  { file: 'base.css', title: 'Base elements' },
  { file: 'components.css', title: 'Shared components' },
];

/** Pages that get a compiled stylesheet. */
const STYLESHEETS = [
  { page: 'popup', source: 'popup/styles/popup.css' },
  { page: 'options', source: 'options/styles/options.css' },
];

const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));

/* ------------------------------------------------------------------ helpers */

/** Keeps the manifest version and the package version from drifting apart. */
function stampVersion(contents) {
  const manifest = JSON.parse(contents);
  manifest.version = pkg.version;
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

function copyStatic({ from, to, transform }) {
  const source = join(SRC, from);
  if (!existsSync(source)) {
    throw new Error(`Static asset missing: src/${from}`);
  }

  const destination = join(DIST, to);
  mkdirSync(dirname(destination), { recursive: true });

  if (statSync(source).isDirectory()) {
    cpSync(source, destination, { recursive: true });
    return;
  }

  const contents = readFileSync(source, 'utf8');
  writeFileSync(destination, transform ? transform(contents) : contents);
}

/**
 * Concatenates the shared design system with a page's own CSS into one file.
 * Cascade order is preserved, and each source keeps a banner so the bundle is
 * still readable when debugging in DevTools.
 */
function writeStylesheet({ page, source }) {
  const parts = SHARED_STYLES.map(({ file, title }) => {
    const path = join(SRC, 'ui', 'styles', file);
    if (!existsSync(path)) throw new Error(`Shared stylesheet missing: src/ui/styles/${file}`);
    return `/* ==== ${title}: ui/styles/${file} ==== */\n${readFileSync(path, 'utf8').trim()}\n`;
  });

  const ownPath = join(SRC, source);
  if (!existsSync(ownPath)) throw new Error(`Page stylesheet missing: src/${source}`);
  parts.push(`/* ==== ${page} page: ${source} ==== */\n${readFileSync(ownPath, 'utf8').trim()}\n`);

  const destination = join(DIST, page, 'styles', `${page}.css`);
  mkdirSync(dirname(destination), { recursive: true });
  writeFileSync(destination, parts.join('\n'), 'utf8');
}
/**
 * Walks the built manifest and every HTML document, then asserts each file they
 * reference actually exists. A build that produces a manifest Chrome refuses to
 * load is worse than a build that fails loudly here.
 */
function verifyOutput() {
  const problems = [];
  const manifest = JSON.parse(readFileSync(join(DIST, 'manifest.json'), 'utf8'));

  const referenced = [
    manifest.background?.service_worker,
    manifest.action?.default_popup,
    manifest.options_ui?.page,
    ...Object.values(manifest.icons ?? {}),
    ...Object.values(manifest.action?.default_icon ?? {}),
  ].filter(Boolean);

  for (const file of referenced) {
    if (!existsSync(join(DIST, file))) problems.push(`manifest references missing ${file}`);
  }

  for (const dir of ['popup', 'options']) {
    const htmlDir = join(DIST, dir);
    if (!existsSync(htmlDir)) continue;

    for (const name of readdirSync(htmlDir)) {
      if (extname(name) !== '.html') continue;
      const html = readFileSync(join(htmlDir, name), 'utf8');
      for (const match of html.matchAll(/(?:src|href)="([^"]+)"/g)) {
        const ref = match[1];
        // Skip same-document anchors and anything off-origin.
        if (ref === undefined || ref.startsWith('#') || /^[a-z]+:/i.test(ref)) continue;
        if (!existsSync(join(htmlDir, ref))) problems.push(`${dir}/${name} -> missing ${ref}`);
      }
    }
  }

  return problems;
}

function report(label) {
  process.stdout.write(`\n${label}\n`);
  const walk = (dir, depth = 0) => {
    for (const entry of readdirSync(dir).sort()) {
      const full = join(dir, entry);
      const stats = statSync(full);
      if (stats.isDirectory()) {
        walk(full, depth + 1);
        continue;
      }
      const size = stats.size < 1024 ? `${stats.size} B` : `${(stats.size / 1024).toFixed(1)} KB`;
      process.stdout.write(`${'  '.repeat(depth + 1)}${entry.padEnd(26)}${size}\n`);
    }
  };
  walk(DIST);
}

/* -------------------------------------------------------------------- build */

function buildOptions() {
  return {
    bundle: true,
    format: 'esm',
    target: ['chrome116'],
    platform: 'browser',
    sourcemap: WATCH ? 'inline' : false,
    minify: !WATCH,
    legalComments: 'none',
    logLevel: 'warning',
    // Chrome supplies this at runtime; failing at build time is the point.
    external: ['chrome'],
  };
}

async function main() {
  if (!WATCH) rmSync(DIST, { recursive: true, force: true });
  mkdirSync(DIST, { recursive: true });

  for (const asset of STATIC) copyStatic(asset);
  for (const sheet of STYLESHEETS) writeStylesheet(sheet);

  const options = buildOptions();
  const contexts = await Promise.all(
    BUNDLES.map((bundle) =>
      esbuild.context({
        ...options,
        entryPoints: [join(SRC, bundle.entry)],
        outfile: join(DIST, bundle.out),
      }),
    ),
  );

  if (WATCH) {
    await Promise.all(contexts.map((context) => context.watch()));
    process.stdout.write('watching for changes…\n');
    return;
  }

  await Promise.all(contexts.map((context) => context.rebuild()));
  await Promise.all(contexts.map((context) => context.dispose()));

  const problems = verifyOutput();
  if (problems.length > 0) {
    const detail = problems.map((problem) => `  - ${problem}`).join('\n');
    process.stderr.write(`\nBuild verification failed:\n${detail}\n`);
    process.exit(1);
  }

  report(`Built ${pkg.name}@${pkg.version} -> ${relative(process.cwd(), DIST)}`);
}

main().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.stack : String(error)}\n`);
  process.exit(1);
});
